import type { ThemeConfig } from "@/components/openpage/blocks/types";

export const defaultTheme: ThemeConfig = {
  bg0: '#ffffff',
  bg1: '#ffffff',
  bg2: '#ffffff',
  bg3: '#f8fafc',
  bg4: '#f1f5f9',
  bg5: '#e2e8f0',
  text0: '#0f172a',
  text1: '#1e293b',
  text2: '#475569',
  text3: '#64748b',
  accent: '#2563eb',
  accentDim: '#1d4ed8',
  ctaButtonColor: '#2563eb',
  borderDefault: '#e2e8f0',
  borderSubtle: '#f1f5f9',
  borderHover: '#cbd5e1',
  fontSans: 'Plus Jakarta Sans',
  fontDisplay: 'Outfit',
  fontMono: 'JetBrains Mono',
  radius: 8,
  radiusLg: 12,
}

export interface ThemePreset {
  id: string
  name: string
  theme: ThemeConfig
}

export const themePresets: ThemePreset[] = [
  {
    id: 'default',
    name: 'Clean White',
    theme: { ...defaultTheme },
  },
  {
    id: 'estate',
    name: 'Estate Gold',
    theme: {
      ...defaultTheme,
      bg0: '#f7f4ef',
      bg1: '#fbfaf7',
      bg2: '#f1ece4',
      bg3: '#e6dfd2',
      bg4: '#d4cfc4',
      bg5: '#c4b8a8',
      text0: '#1a1612',
      text1: '#4a4238',
      text2: '#7a7268',
      text3: '#a39a8e',
      accent: '#b8860b',
      accentDim: '#9a6f08',
      borderDefault: '#e4ddd2',
      borderSubtle: '#efeae2',
      borderHover: '#d6cec2',
      fontSans: 'Plus Jakarta Sans',
      fontDisplay: 'Cormorant Garamond',
      radius: 12,
      radiusLg: 20,
    },
  },
  {
    id: 'ivory',
    name: 'Ivory',
    theme: {
      ...defaultTheme,
      bg0: '#fdfcfa',
      bg1: '#f5f3ef',
      bg2: '#edebe5',
      bg3: '#e0ddd6',
      bg4: '#ccc8bf',
      bg5: '#b0ab9f',
      text0: '#1c1917',
      text1: '#44403c',
      text2: '#78716c',
      text3: '#a8a29e',
      accent: '#0f1424',
      accentDim: '#0f1424',
      borderDefault: '#e5e2db',
      borderSubtle: '#f0ede7',
      borderHover: '#d5d0c8',
      fontSans: 'Plus Jakarta Sans',
      fontDisplay: 'Sora',
      radius: 10,
      radiusLg: 16,
    },
  },
  {
    id: 'clean',
    name: 'Clean',
    theme: {
      ...defaultTheme,
      bg0: '#ffffff',
      bg1: '#f8f9fa',
      bg2: '#f1f3f5',
      bg3: '#e9ecef',
      bg4: '#dee2e6',
      bg5: '#ced4da',
      text0: '#212529',
      text1: '#495057',
      text2: '#868e96',
      text3: '#adb5bd',
      accent: '#228be6',
      accentDim: '#1c7ed6',
      borderDefault: '#e9ecef',
      borderSubtle: '#f1f3f5',
      borderHover: '#dee2e6',
      fontSans: 'Inter',
      fontDisplay: 'Inter',
      radius: 8,
      radiusLg: 12,
    },
  },
  {
    id: 'sand',
    name: 'Sand',
    theme: {
      ...defaultTheme,
      bg0: '#faf8f5',
      bg1: '#f2efe8',
      bg2: '#e8e4db',
      bg3: '#ddd8cd',
      bg4: '#c8c2b5',
      bg5: '#b3ab9c',
      text0: '#2c2418',
      text1: '#5c5347',
      text2: '#8a8074',
      text3: '#b0a798',
      accent: '#d97706',
      accentDim: '#b45309',
      borderDefault: '#e2ddd4',
      borderSubtle: '#ebe8e1',
      borderHover: '#d5cfc4',
      fontSans: 'Nunito Sans',
      fontDisplay: 'Outfit',
      radius: 10,
      radiusLg: 14,
    },
  },
  {
    id: 'amber',
    name: 'Amber',
    theme: {
      ...defaultTheme,
      bg0: '#171210',
      bg1: '#1e1816',
      bg2: '#26201c',
      bg3: '#302925',
      bg4: '#3d3530',
      bg5: '#504640',
      text0: '#faf6f0',
      text1: '#d4c8b8',
      text2: '#a89a88',
      text3: '#7d7062',
      accent: '#e8a838',
      accentDim: '#cc8f20',
      borderDefault: '#352e28',
      borderSubtle: '#28211b',
      borderHover: '#443c35',
      fontSans: 'Outfit',
      fontDisplay: 'Outfit',
      radius: 6,
      radiusLg: 10,
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    theme: {
      ...defaultTheme,
      bg0: '#0a1628',
      bg1: '#101e32',
      bg2: '#162740',
      bg3: '#1d3050',
      bg4: '#264060',
      bg5: '#305575',
      text0: '#eef4ff',
      text1: '#b0c8e8',
      text2: '#7a9cc0',
      text3: '#506d90',
      accent: '#3b82f6',
      accentDim: '#2563eb',
      borderDefault: '#1e3250',
      borderSubtle: '#162640',
      borderHover: '#2a4468',
      fontSans: 'Inter',
      fontDisplay: 'Sora',
    },
  },
  {
    id: 'rose',
    name: 'Rosé',
    theme: {
      ...defaultTheme,
      bg0: '#16101a',
      bg1: '#1e1620',
      bg2: '#261e28',
      bg3: '#302632',
      bg4: '#3e3340',
      bg5: '#504250',
      text0: '#faf4f8',
      text1: '#d0bcc8',
      text2: '#a08898',
      text3: '#786575',
      accent: '#f472b6',
      accentDim: '#ec4899',
      borderDefault: '#30252e',
      borderSubtle: '#241c25',
      borderHover: '#402e3a',
      fontSans: 'DM Sans',
      fontDisplay: 'Raleway',
      radius: 12,
      radiusLg: 18,
    },
  },
  {
    id: 'purple-haze',
    name: 'Purple Haze',
    theme: {
      ...defaultTheme,
      bg0: '#100c1a',
      bg1: '#16111f',
      bg2: '#1e1828',
      bg3: '#262033',
      bg4: '#302a40',
      bg5: '#3e3650',
      text0: '#f5f0ff',
      text1: '#c4b5fd',
      text2: '#8b7cbf',
      text3: '#6b5c8f',
      accent: '#8b5cf6',
      accentDim: '#7c3aed',
      borderDefault: '#2a2240',
      borderSubtle: '#1e1832',
      borderHover: '#38304f',
      fontSans: 'Manrope',
      fontDisplay: 'Sora',
      radius: 10,
      radiusLg: 14,
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    theme: {
      ...defaultTheme,
      bg0: '#0f1114',
      bg1: '#161a1e',
      bg2: '#1e2228',
      bg3: '#252a32',
      bg4: '#2e353e',
      bg5: '#3a4250',
      text0: '#f0f4f8',
      text1: '#94a3b8',
      text2: '#64748b',
      text3: '#475569',
      accent: '#06b6d4',
      accentDim: '#0891b2',
      borderDefault: '#252a32',
      borderSubtle: '#1c2028',
      borderHover: '#323a45',
      fontSans: 'Work Sans',
      fontDisplay: 'Space Grotesk',
      radius: 6,
      radiusLg: 10,
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    theme: {
      ...defaultTheme,
      bg0: '#0a120c',
      bg1: '#101a13',
      bg2: '#16221a',
      bg3: '#1e2c22',
      bg4: '#26382a',
      bg5: '#304434',
      text0: '#eef8f0',
      text1: '#a0c8a8',
      text2: '#6ea078',
      text3: '#4e7858',
      accent: '#10b981',
      accentDim: '#059669',
      borderDefault: '#1e3022',
      borderSubtle: '#162418',
      borderHover: '#2c4230',
      fontSans: 'Plus Jakarta Sans',
      fontDisplay: 'DM Sans',
      radius: 8,
      radiusLg: 14,
    },
  },
  {
    id: 'aurelia',
    name: 'Aurelia Reserve',
    theme: {
      ...defaultTheme,
      bg0: '#f7f4ef',
      bg1: '#fbfaf7',
      bg2: '#f1ece4',
      bg3: '#e6dfd2',
      bg4: '#d4cfc4',
      bg5: '#c4b8a8',
      text0: '#1a1612',
      text1: '#4a4238',
      text2: '#7a7268',
      text3: '#a39a8e',
      accent: '#1a1612',
      accentDim: '#3a322c',
      borderDefault: '#e4ddd2',
      borderSubtle: '#efeae2',
      borderHover: '#d6cec2',
      fontSans: 'Montserrat',
      fontDisplay: 'Cormorant Garamond',
      radius: 14,
      radiusLg: 24,
    },
  },
  {
    id: 'vista-red',
    name: 'Vista Framed',
    theme: {
      ...defaultTheme,
      bg0: '#faf8f5',
      bg1: '#ffffff',
      bg2: '#f3f0eb',
      bg3: '#e8e4dc',
      bg4: '#d6d0c6',
      bg5: '#c0b8ac',
      text0: '#12101c',
      text1: '#3d3a4a',
      text2: '#6b6778',
      text3: '#9a96a5',
      accent: '#e11d2e',
      accentDim: '#be1230',
      borderDefault: '#e8e4dc',
      borderSubtle: '#f0ece6',
      borderHover: '#d6d0c6',
      fontSans: 'Inter',
      fontDisplay: 'Playfair Display',
      radius: 16,
      radiusLg: 32,
    },
  },
  {
    id: 'future-home',
    name: 'Future Home',
    theme: {
      ...defaultTheme,
      bg0: '#fcf9f1',
      bg1: '#ffffff',
      bg2: '#f5f1e8',
      bg3: '#ebe5d8',
      bg4: '#d9d1c0',
      bg5: '#c4bba8',
      text0: '#1c1917',
      text1: '#44403c',
      text2: '#78716c',
      text3: '#a8a29e',
      accent: '#ff4b4b',
      accentDim: '#e11d2e',
      borderDefault: '#ebe5d8',
      borderSubtle: '#f5f1e8',
      borderHover: '#d9d1c0',
      fontSans: 'Inter',
      fontDisplay: 'Playfair Display',
      radius: 14,
      radiusLg: 22,
    },
  },
  {
    id: 'modern-living',
    name: 'Modern Living',
    theme: {
      ...defaultTheme,
      bg0: '#f5f5f7',
      bg1: '#ffffff',
      bg2: '#ececef',
      bg3: '#e0e0e4',
      bg4: '#cfcfd4',
      bg5: '#b8b8be',
      text0: '#0e121a',
      text1: '#3a3f4a',
      text2: '#6b7280',
      text3: '#9ca3af',
      accent: '#ff5252',
      accentDim: '#e53935',
      borderDefault: '#e5e7eb',
      borderSubtle: '#f3f4f6',
      borderHover: '#d1d5db',
      fontSans: 'Inter',
      fontDisplay: 'Playfair Display',
      radius: 12,
      radiusLg: 20,
    },
  },
  {
    id: 'investment-hub',
    name: 'Investment Hub',
    theme: {
      ...defaultTheme,
      bg0: '#f7f7f5',
      bg1: '#ffffff',
      bg2: '#efefeb',
      bg3: '#e2e2dc',
      bg4: '#cecec6',
      bg5: '#b8b8ae',
      text0: '#171717',
      text1: '#404040',
      text2: '#737373',
      text3: '#a3a3a3',
      accent: '#171717',
      accentDim: '#404040',
      borderDefault: '#e5e5e5',
      borderSubtle: '#f5f5f5',
      borderHover: '#d4d4d4',
      fontSans: 'Inter',
      fontDisplay: 'Playfair Display',
      radius: 16,
      radiusLg: 28,
    },
  },
  {
    id: 'vista-curve',
    name: 'Vista Curve',
    theme: {
      ...defaultTheme,
      bg0: '#fffdf8',
      bg1: '#ffffff',
      bg2: '#faf6ee',
      bg3: '#f0e9dc',
      bg4: '#e0d6c4',
      bg5: '#cfc3ad',
      text0: '#1c1917',
      text1: '#44403c',
      text2: '#78716c',
      text3: '#a8a29e',
      accent: '#ef4444',
      accentDim: '#dc2626',
      borderDefault: '#efe6d6',
      borderSubtle: '#faf6ee',
      borderHover: '#e0d6c4',
      fontSans: 'Inter',
      fontDisplay: 'Playfair Display',
      radius: 16,
      radiusLg: 28,
    },
  },
]

export function isDarkColor(hex?: string): boolean {
  if (!hex || typeof hex !== 'string') return true;
  const clean = hex.replace('#', '');
  if (clean.length === 3) {
    const r = parseInt(clean[0] + clean[0], 16);
    const g = parseInt(clean[1] + clean[1], 16);
    const b = parseInt(clean[2] + clean[2], 16);
    return (0.299 * r + 0.587 * g + 0.114 * b) < 140;
  }
  if (clean.length >= 6) {
    const r = parseInt(clean.slice(0, 2), 16);
    const g = parseInt(clean.slice(2, 4), 16);
    const b = parseInt(clean.slice(4, 6), 16);
    return (0.299 * r + 0.587 * g + 0.114 * b) < 140;
  }
  return false;
}

export function resolveTheme(partial?: Partial<ThemeConfig>): ThemeConfig {
  if (!partial) return defaultTheme;
  const isDarkFallback = !partial.bg0 || isDarkColor(partial.bg0) || partial.bg0 === '#09090b' || partial.bg0 === '#000000' || partial.bg0 === '#0f0f12' || partial.bg0 === '#18181b';
  if (isDarkFallback) {
    return {
      ...defaultTheme,
      ...partial,
      bg0: '#ffffff',
      bg1: '#ffffff',
      bg2: '#f8fafc',
      bg3: '#f1f5f9',
      bg4: '#e2e8f0',
      bg5: '#cbd5e1',
      text0: '#0f172a',
      text1: '#1e293b',
      text2: '#475569',
      text3: '#64748b',
      borderDefault: '#e2e8f0',
      borderSubtle: '#f1f5f9',
      borderHover: '#cbd5e1',
    };
  }
  return { ...defaultTheme, ...partial };
}

export function hexToRgb(hex: string): string {
  const h = hex.replace('#', '')
  const r = parseInt(h.slice(0, 2), 16)
  const g = parseInt(h.slice(2, 4), 16)
  const b = parseInt(h.slice(4, 6), 16)
  return `${r}, ${g}, ${b}`
}

export function themeToCSS(theme: ThemeConfig): Record<string, string> {
  const rgb = hexToRgb(theme.accent)
  return {
    '--op-bg': theme.bg0,
    '--op-text': theme.text0,
    '--color-bg-0': theme.bg0,
    '--color-bg-1': theme.bg1,
    '--color-bg-2': theme.bg2,
    '--color-bg-3': theme.bg3,
    '--color-bg-4': theme.bg4,
    '--color-bg-5': theme.bg5,
    '--color-text-0': theme.text0,
    '--color-text-1': theme.text1,
    '--color-text-2': theme.text2,
    '--color-text-3': theme.text3,
    '--color-green': theme.ctaButtonColor || theme.accent,
    '--color-cta': theme.ctaButtonColor || theme.accent,
    '--color-green-dim': theme.accentDim,
    '--color-green-glow': `rgba(${rgb}, 0.12)`,
    '--color-green-glow2': `rgba(${rgb}, 0.06)`,
    '--color-border-default': theme.borderDefault,
    '--color-border-subtle': theme.borderSubtle,
    '--color-border-hover': theme.borderHover,
    '--color-accent-rgb': rgb,
    '--font-sans': `"${theme.fontSans}", -apple-system, system-ui, sans-serif`,
    '--font-display': `"${theme.fontDisplay}", system-ui, sans-serif`,
    '--font-mono': `"${theme.fontMono}", ui-monospace, monospace`,
    '--radius-default': `${theme.radius}px`,
    '--radius-lg': `${theme.radiusLg}px`,
  }
}

export const googleFontOptions = [
  'DM Sans',
  'Inter',
  'Space Grotesk',
  'Poppins',
  'Manrope',
  'Outfit',
  'Plus Jakarta Sans',
  'Playfair Display',
  'Cinzel',
  'Montserrat',
  'Cormorant Garamond',
  'Sora',
  'Nunito Sans',
  'Work Sans',
  'Rubik',
  'Raleway',
  'Roboto',
  'Lora',
  'JetBrains Mono',
  'Fira Code',
  'Source Code Pro',
]
